### ISSUE TITLE
build_query doesn't respect enrollments table contract

### ISSUE THREAD

**Issue by SuYoungHong** [mozilla/mozanalysis#117]
When calculating Days of Use metric for a given window period, there are instances of clients producing more Days of Use then possible given the window period. 

If window is 14 days, only 14 days of use is possible. However, we see cases of greater then 14 days. 

Interesting observation: the maximum number of days of use we see seem to always be: 
* (# of branches) x (possible days)

Example: 

pulled data using: [this notebook](https://colab.research.google.com/drive/1LY_cCOXepUHxt5oAUKDvFGtG2RB1RL4d#scrollTo=_TeZxV3r2k3d&line=10&uniqifier=1)

```
use_days_wk0wk1 = exp.get_single_window_data(
    bq_context=bq_context,
    metric_list=[
        mmd.days_of_use, 
        imported_items, 
        imported_logins, 
        enabled_themes
    ],
    last_date_full_data='2020-11-18',
    analysis_start_days=0,
    analysis_length_days=14
)
```

Table here: `moz-fx-data-bq-data-science.shong.2020_11_18_bug_1668928_message_multi_stage_aboutwelcome_zero_stage_release_82_83_0c385114523c`

Example of issue: 

```
select *
from `moz-fx-data-bq-data-science.shong.2020_11_18_bug_1668928_message_multi_stage_aboutwelcome_zero_stage_release_82_83_0c385114523c`
WHERE days_of_use > 14
```

and 

```
select days_of_use, count(*)
from `moz-fx-data-bq-data-science.shong.2020_11_18_bug_1668928_message_multi_stage_aboutwelcome_zero_stage_release_82_83_0c385114523c`
GROUP BY 1
```

**Comment by felixlawrence** [comment]
The problem is that in `DataSource.build_query()` in `metrics/__init__.py`, we join `enrollments e` to `clients_daily ds` on client_id and submission_date, and intentionally don't join on `branch`. Unintentionally, we don't `GROUP BY e.branch`, so if there are enrollment events for _n_ branches then we join to each row in `clients_daily` _n_ times. Ouch. At least this error is symmetric across branches, and associated with data that was already garbage. But still, ouch.

At first I thought the solution would be to `GROUP BY e.*` in `DataSource.build_query()` and then do a stricter join in `Experiment._build_metrics_query_bits()`. But `JOIN ONE` isn't a thing, and I don't think `GROUP BY e.*` is a thing, particularly when custom enrollment queries are involved, not even Python knows what columns are in the enrollments query.

So instead, we should embrace that `DataSource.build_query()` and `Experiment._build_metrics_query_bits()` both only use `client_id`, `enrollment_date`, `analysis_window_start`, and `analysis_window_end` in their join conditions, and instead of joining `FROM enrollments e` we should join

```
FROM (
            SELECT DISTINCT 
                e.client_id,
                e.enrollment_date,
                e.analysis_window_start, 
                e.analysis_window_end 
            FROM enrollments
        ) e
```

in `DataSource.build_query()`, and add `enrollment_date` to the `USING` in `Experiment._build_metrics_query_bits()`

**Comment by tdsmith** [comment]
The most parsimonious change would be to also select and group by e.branch in query_bits, right? We don't rely on the branch in the metric data_source so that seems okay. The enrollments table contract is SORT OF defined (#93) and should you stray from it, God help you, is not an *un*reasonable take.

> I don't think GROUP BY e.* is a thing, particularly when custom enrollment queries are involved, not even Python knows what columns are in the enrollments query.

I had the fleeting thought that we could build some assertions into a BigQuery script about the enrollments query, but #116 means that would take a little more finessing / a separate execution step. Still possible, though, and I'm warming to the idea of executing some assertions about the data before we operate on it as I think about it.

Similarly, we _could_ rely on BigQuery to tell us what all the columns are, though I like that rather less.

**Comment by tdsmith** [comment]
Thanks very much for finding and reporting this, @SuYoungHong!

**Comment by felixlawrence** [comment]
Yeah, grouping by e.branch in `DataSource.build_query()` and then joining on it in `Experiment._build_metrics_query_bits()` was my first instinct. I then thought "well really what we want to do is take the set of rows in `enrollments` and add extra columns to those rows, without adding, merging or deleting rows." Hence the desire for `GROUP BY e.*`. (E.g. we almost should be grouping by enrollment_date too)

When I accepted that we can't have nice things, I switched strategy: in `DataSource.build_query()`, let's de-duplicate the `enrollments` view among the only columns that actually get used in that subquery, and then we can make sure to join the results back to the full list of enrollments in `Experiment._build_metrics_query_bits()` using exactly these columns.

This solution should be robust to enrollment queries that surprise us, e.g. by having multiple enrollment rows for a client_id and a branch, but with different submission_dates.

**Comment by tdsmith** [comment]
>  I then thought "well really what we want to do is take the set of rows in enrollments and add extra columns to those rows, without adding, merging or deleting rows." Hence the desire for GROUP BY e.*. (E.g. we almost should be grouping by enrollment_date too)

I think the enrollments table contract is that there's one row per (client_id, branch), and as long as we follow that everywhere, we won't get adding or merging or deleting. Adding enrollment_date to the join just makes the join more expensive for no added safety.

So I think we _have_ the nice thing and we can add some assertions that the enrollment table follows the contract, which is important independent of making this join operate correctly.

I buy that the subquery approach works but I like it less for a couple of reasons:
* including just a handful of defined columns means means that we can't derive metrics that reference a column in the enrollments table: this is a bit of a speculative need but it's come up in conversation; if we want to relate user activity in the experiment to user activity before the experiment in a way that's finer-toothed than segmenting, I think this is a capability that we'd want
* more subqueries means more query complexity and we don't know where our budget for that is

So I think adding branch to the join is a good solution.

**Comment by felixlawrence** [comment]
> I think the enrollments table contract is that there's one row per (client_id, branch), and as long as we follow that everywhere, we won't get adding or merging or deleting. Adding enrollment_date to the join just makes the join more expensive for no added safety.

Alas no: if a client_id has enrollments in two different branches with two different `enrollment_date`, then the analysis windows for the two enrollments are going to lie over a different set of calendar dates, and that won't be respected by the `GROUP BY e.client_id, e.analysis_window_start, e.analysis_window_end` in `DataSource.build_query()`. So we really _should_ have that extra group by `enrollment_date` in `DataSource.build_query()` and the extra join on `enrollment_date` in `Experiment._build_metrics_query_bits()`. This demonstrates that there's plenty of room for subtle oversight here!

If we don't do this, it's not the end of the world: the affected clients already have pretty screwy (meaningless-to-the-experiment?) data, and either way I _think_ there's no branch bias introduced here even when branches are imbalanced? So this _might_ be outweighed by your arguments... and surely there's no more space under the rug for other unknown unknown issues to creep out from where this `enrollment_date` issue just appeared?
