### ISSUE TITLE
Update docs to reflect metrics migration

### ISSUE THREAD

**Issue by rebecca-burwei** [mozilla/mozanalysis#154]
[Docs like these](https://mozilla.github.io/mozanalysis/api/metrics/desktop.html) are empty even though the namespaces are not.

**Comment by jaredsnyder** [comment]
It looks like the metrics don't have docs because there is no docstrings from which to generate them.  Given this issue https://github.com/mozilla/mozanalysis/issues/171  it looks like there is some desire to deprecate them anyway so we might be good to close this one, or at least link it to the issue that removes these functions
