### ISSUE TITLE
Allow for extra groupers in get_per_client_data

### ISSUE THREAD

**Issue by benmiroglio** [mozilla/mozanalysis#46]
Sometimes I like to look at different facets of the experiment data, i.e. by submission_date or by country. By country is super important for search-based experiments as we have different location-based contracts.

i.e. https://github.com/mozilla/mozanalysis/blob/master/src/mozanalysis/experiment.py#L350

could do something like 

```
.groupBy(
     *[enrollments.client_id, enrollments.branch] + extra_groupers
)
```

with `extra_groupers` defaulting to an empty list. These extra groupers would need to be in the `data_source` table.

Let me know your thoughts on this @felixlawrence.

**Comment by benmiroglio** [comment]
days_since_enrollment is another alternative here as well instead of submission_date

**Comment by felixlawrence** [comment]
Yep, I haven't communicated the roadmap clearly enough but this is certainly on it. I refer to these subsets of enrollments as "segments" and the rule of thumb for constructing them is that they should be identified by left-joining the `enrollments` dataframe to data that was collected at or before time of enrollment.

I haven't tried to do this sort of thing in Spark yet - if you blaze a trail then please let me know, otherwise I'll get to it after we have a metrics library.

* [x] decide to "left join on enrollments"
* [x] decide on common data format for analyses
* [x] agree on and merge querying code to mozanalysis
* [ ] agree on and merge bootstrap & bayesian binomial code to mozanalysis
* [ ] define & write code for guardrail metrics (5 core metrics)
* [ ] define & write code for blessed metrics (other metrics)
* [ ] decide that segmenting is a good idea
* [ ] define & write code for blessed segments
* [ ] implement code for conveniently querying analyzing and visualizing time series

**Comment by felixlawrence** [comment]
As of mozanalysis 2019.10.0, you can achieve this if you take the `enrollments` DataFrame, add extra columns with segment information (e.g. have a 'country' column), and pass the resulting DataFrame into `get_per_client_data()` as the `enrollments` DataFrame.

This is still more manual than it should be; i.e. you need to work out how to add that column yourself, and there's nothing that suggests this pattern. A more friendly flow, with canned segments, will arrive as formal segmentation support.

**Comment by jaredsnyder** [comment]
Addressed now with Segments
