### ISSUE TITLE
Percentile bootstrap

### ISSUE THREAD

**Issue by tdsmith** [mozilla/mozanalysis#5]
Thanks for working on this! I noticed that this uses a "percentile bootstrap," computing the confidence interval for the sample statistic by directly sampling the quantiles of the statistic on the bootstraps.

I've noticed that sources tend to prefer observing the difference between the bootstrap statistic and the sample statistic, and then using that to bound the difference between the sample statistic and the true value. 

Basically, it's using the same quantiles of the statistic on the bootstrap samples, but the signs are switched with respect to its difference from the sample statistic.

There's a brief treatment of the difference here: https://en.wikipedia.org/wiki/Bootstrapping_(statistics)#Methods_for_bootstrap_confidence_intervals

and a longer explanation here: https://stats.stackexchange.com/a/357498/86451

A demonstration of how the calculations for the two methods differ and an illustration of a pathological case where the percentile bootstrap is biased in the wrong direction in the presence of an asymmetrical bootstrap sample distribution are here: https://dbc-caf9527b-e073.cloud.databricks.com/#notebook/33549

I think this should probably use the basic formulation since the computational complexity is similar (though we're probably in trouble if we find ourselves in a place where it makes a difference).

**Comment by sunahsuh** [comment]
Thanks for the pointers & the links! As you alluded to, given the general size of our samples (and that the overhead for this implementation only really makes sense if we have very large samples) I'd be surprised if this turned out to be an issue but since this might be useful outside of Moz it seems there's no downside and only upside to switching the formula. Thankfully we broke out the CI calc into a separate method in the code so it's just a matter of swapping out a call :) We can add the basic bootstrap CI calc and make that the default and add a parameter to let the caller use a different CI method if they'd like. My hope was that we'd implement the BCa algorithm down the line since it seems like the most robust method and comparatively the extra computation doesn't seem like a huge deal.

Thanks for the robust science review! Can I assume we can tag you on future reviews that implement stats methods? 😄

**Comment by tdsmith** [comment]
> Can I assume we can tag you on future reviews that implement stats methods?

Tag away; I'll do my best.
