### ISSUE TITLE
[Feature Request] Generate a view alongside the table written to GCP

### ISSUE THREAD

**Issue by teonbrooks** [mozilla/mozanalysis#73]
Is there an option to make a view in addition to the table that is written to gcp. one use case is to be able to spotcheck when investigating a report. views bundle the sql that is written with it. what I envision is that the view and the table are written with the same string as it is present and a view is generated with an appended `_view` to allow for both to exist. the table prevents rerunning the sql while the view allows for inspection of how said table was written.

**Comment by teonbrooks** [comment]
cc: @tdsmith. I chatted with @felixlawrence earlier about this. I really like the hashing of the query and that the table generation saves on scanning more data. I read that you can't save the query to your workspace via cli (only through their console ui). I think it would be great to include a view of the table that is essentially read-only that shows the originating sql. mozanalysis could continue to function as-is, but it would provide some introspection into the intermediate steps

**Comment by felixlawrence** [comment]
Yeah, there are pros and cons to each option.

Save the results as a table:
1. Don't need to re-run slow/expensive query e.g. each time colab resets the notebook's kernel
2. Have an archival copy of the results, in case the data sources change or go away
3. Might cause issues with retention policies and/or data deletion policies in the future? Or might solve them if this form of the data is deemed OK to keep
4. No "view source" in bigquery; you have to use mozanalysis to see the query that generated the table

Save the results as a view:
1. Do need to re-run the slow/expensive query - unless BQ does some sort of view caching?
2. No archival copy of the results if the underlying data changes
3. No problems with retention/deletion policies because the data isn't saved anywhere new
4. Can use BQ to see the query that underpins the view - easier to access for people who don't know about the private method `._build_query()`.

In my opinion point (1) is the biggest practical difference here, which makes me lean towards keeping things as a table, but others have different workflows and needs.

The data engineers are likely to have some preferences, opinions or recommendations here - @scholtzan? Or their sleeves may even contain some BQ solution that lets us have our cake and eat it too?

**Comment by tdsmith** [comment]
Stepping back a bit, I think the problem you're describing is that you want to be able to see the SQL for an experiment analysis generated by mozanalysis.

I think this use case was addressed by #66 -- you can call build_query() yourself to get the SQL for your query and memorialize it or run it however you wish.

If we actually wrote out a view I think it would be a mistake to ever try and use it, which feels odd -- if we just want it as documentation, we should find another place or way to save it, which I think build_query provides.

> No archival copy of the results if the underlying data changes

AIUI CCPA requires that there will never be an immutable archival copy of per-user data; the underlying data _will_ change, and we _will_ be forced to update the dependent datasets, so I don't think we can make strong promises about repeatable analysis. Summary stats are forever but I'm not totally confident we want to produce those with SQL anyway.

**Comment by teonbrooks** [comment]
> If we actually wrote out a view I think it would be a mistake to ever try and use it, which feels odd -- if we just want it as documentation, we should find another place or way to save it, which I think build_query provides.

oh ok, felix demoed build_query with me when we met and I think the solution would be to just write out a `.sql` for memorializing the creation using `build_query`. I think that should be sufficient for our use case. is the hash readily accessible that is used as the table label?

**Comment by teonbrooks** [comment]
closing this because issue is mostly addressed with https://github.com/mozilla/mozanalysis/pull/66.
@tdsmith, just curious, is there interest in adding a `dry_run` parameter as mentioned in the above PR or is the suggested path to use `build_query` if we want a copy of the query?

**Comment by teonbrooks** [comment]
closing this because issue is mostly addressed with #66.
@tdsmith, just curious, is there interest in adding a dry_run parameter as mentioned in the above PR or is the suggested path to use build_query if we want a copy of the query?
